# Generated by Django 3.2.13 on 2022-06-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=120, verbose_name='HR Name')),
                ('h_email_id', models.EmailField(max_length=254, verbose_name='HR Email Address')),
                ('h_address', models.CharField(max_length=300)),
                ('h_mob_num', models.CharField(max_length=10, verbose_name='HR Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=120, verbose_name='Intern Name')),
                ('i_email_address', models.EmailField(max_length=254, verbose_name='Intern Email Address')),
                ('i_mob_num', models.CharField(max_length=10, verbose_name='Intern Mobile Number')),
                ('i_address', models.CharField(max_length=300)),
                ('i_job_position', models.CharField(max_length=120, verbose_name='Job Position')),
                ('i_stipend', models.CharField(max_length=3, verbose_name='Stipend')),
                ('i_join_date', models.DateTimeField(verbose_name='Join Date')),
                ('i_description', models.CharField(max_length=150, verbose_name='Job Description')),
                ('hr_email', models.EmailField(max_length=150, verbose_name='HR mail')),
                ('hr_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intern_register.hr')),
            ],
        ),
    ]
