# Generated by Django 3.2.13 on 2022-06-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_register', '0002_alter_intern_i_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='hr_email',
            field=models.EmailField(max_length=150, null=True, verbose_name='HR Mail'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='i_address',
            field=models.CharField(max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='i_email_address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='i_mob_num',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='i_name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
    ]
